# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Priyanka Mondal"
title_separator          : "-"
name                     : &name "Priyanka Mondal"
description              : &description "I am a PhD Candidate at the University of California, Santa Cruz."
url                      : "" #https://priyanka-mondal.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "Priyanka-Mondal/priyanka-mondal.github.io"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page


# Site Author
author:
  name             : "Priyanka Mondal"
  avatar           : "priyankajpg.jpg"
  bio              : Ph.D. Candidate
  employer         : ""
  email            : ""
  googlescholar    : "https://scholar.google.com/citations?user=xHRP7lkAAAAJ&hl=en"
  github           : "Priyanka-Mondal"
  linkedin         : "priyanka-mondal-621a1548"



# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-feed

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!-- more -->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

